import { FinancialStatement } from './../models/financial-statement.model';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class FakeDataService {
  constructor() {}

  fakeDataList: FinancialStatement[] = [
    {
      id: 1,
      name: 'Jilleen',
      gender: 'Feminino',
      cardNumber: 3528926078549220,
      type: 'jcb',
      status: 'EE',
      cardLock: false,
      cardEmission: '68703-126',
      changeChipPassword: 'Cebus albifrons',
      cardPasswordValidation: 'Tiliqua scincoides',
      travelNoticeException: 'Damaliscus dorcas',
      birthDate: '16/11/2021',
      date: '25/10/2021',
      cardChipPassword: '********',
    },
    {
      id: 2,
      name: 'Blakelee',
      gender: 'Feminino',
      cardNumber: 36256471612206,
      type: 'diners-club-international',
      status: 'NTL',
      cardLock: true,
      cardEmission: '63323-648',
      changeChipPassword: 'Grus antigone',
      cardPasswordValidation: 'Cygnus buccinator',
      travelNoticeException: 'Phylurus milli',
      birthDate: '02/10/2021',
      date: '16/08/2021',
      cardChipPassword: '********',
    },
    {
      id: 3,
      name: 'Noell',
      gender: 'Feminino',
      cardNumber: 5602210966060034000,
      type: 'china-unionpay',
      status: 'TQQQ',
      cardLock: false,
      cardEmission: '10819-1080',
      changeChipPassword: 'Colobus guerza',
      cardPasswordValidation: 'Macropus fuliginosus',
      travelNoticeException: 'Gyps bengalensis',
      birthDate: '22/03/2022',
      date: '12/06/2021',
      cardChipPassword: '********',
    },
    {
      id: 4,
      name: 'Ad',
      gender: 'Masculino',
      cardNumber: 5476672137117321,
      type: 'mastercard',
      status: 'ELC',
      cardLock: true,
      cardEmission: '55289-997',
      changeChipPassword: 'Hippotragus niger',
      cardPasswordValidation: 'Macropus robustus',
      travelNoticeException: 'Dolichitus patagonum',
      birthDate: '21/07/2021',
      date: '25/12/2021',
      cardChipPassword: '********',
    },
    {
      id: 5,
      name: 'Gibb',
      gender: 'Masculino',
      cardNumber: 4903096396522713000,
      type: 'switch',
      status: 'FTXH',
      cardLock: false,
      cardEmission: '65044-1340',
      changeChipPassword: 'Psophia viridis',
      cardPasswordValidation: 'Laniarius ferrugineus',
      travelNoticeException: 'Cracticus nigroagularis',
      birthDate: '11/07/2021',
      date: '19/05/2021',
      cardChipPassword: '********',
    },
    {
      id: 6,
      name: 'Camille',
      gender: 'Feminino',
      cardNumber: 3533466990103346,
      type: 'jcb',
      status: 'JASNW',
      cardLock: true,
      cardEmission: '42507-110',
      changeChipPassword: 'Nyctereutes procyonoides',
      cardPasswordValidation: 'Mustela nigripes',
      travelNoticeException: 'Varanus salvator',
      birthDate: '02/08/2021',
      date: '26/04/2021',
      cardChipPassword: '********',
    },
    {
      id: 7,
      name: 'Avery',
      gender: 'Masculino',
      cardNumber: 3547366748632568,
      type: 'jcb',
      status: 'SPWR',
      cardLock: false,
      cardEmission: '64395-0001',
      changeChipPassword: 'Varanus sp.',
      cardPasswordValidation: 'Myrmecophaga tridactyla',
      travelNoticeException: 'Macropus rufogriseus',
      birthDate: '06/07/2021',
      date: '20/11/2021',
      cardChipPassword: '********',
    },
    {
      id: 8,
      name: 'Cordie',
      gender: 'Masculino',
      cardNumber: 30235586525749,
      type: 'diners-club-carte-blanche',
      status: 'GSIT',
      cardLock: true,
      cardEmission: '13668-141',
      changeChipPassword: 'Merops nubicus',
      cardPasswordValidation: 'Varanus salvator',
      travelNoticeException: 'Orcinus orca',
      birthDate: '14/06/2021',
      date: '16/01/2022',
      cardChipPassword: '********',
    },
    {
      id: 9,
      name: 'Tomas',
      gender: 'Masculino',
      cardNumber: 3550227468122418,
      type: 'jcb',
      status: 'BHK',
      cardLock: false,
      cardEmission: '50563-152',
      changeChipPassword: 'Isoodon obesulus',
      cardPasswordValidation: 'Speotyte cuniculata',
      travelNoticeException: 'Meleagris gallopavo',
      birthDate: '13/12/2021',
      date: '11/08/2021',
      cardChipPassword: '********',
    },
    {
      id: 10,
      name: 'Carmella',
      gender: 'Feminino',
      cardNumber: 3557552312974273,
      type: 'jcb',
      status: 'ISG',
      cardLock: false,
      cardEmission: '24909-606',
      changeChipPassword: 'unavailable',
      cardPasswordValidation: 'Crotalus triseriatus',
      travelNoticeException: 'Bucephala clangula',
      birthDate: '03/10/2021',
      date: '02/10/2021',
      cardChipPassword: '********',
    },
    {
      id: 11,
      name: 'Mellie',
      gender: 'Feminino',
      cardNumber: 3565586006984065,
      type: 'jcb',
      status: 'QCRH',
      cardLock: false,
      cardEmission: '35000-064',
      changeChipPassword: 'Ovis canadensis',
      cardPasswordValidation: 'Ara ararauna',
      travelNoticeException: 'Nucifraga columbiana',
      birthDate: '28/06/2021',
      date: '20/03/2021',
      cardChipPassword: '********',
    },
    {
      id: 12,
      name: 'Christian',
      gender: 'Masculino',
      cardNumber: 5007660972227527,
      type: 'mastercard',
      status: 'CUBI^E',
      cardLock: false,
      cardEmission: '21130-254',
      changeChipPassword: 'Eubalaena australis',
      cardPasswordValidation: 'Dusicyon thous',
      travelNoticeException: 'unavailable',
      birthDate: '31/12/2021',
      date: '07/12/2021',
      cardChipPassword: '********',
    },
    {
      id: 13,
      name: 'Sutherlan',
      gender: 'Feminino',
      cardNumber: 3550142406173607,
      type: 'jcb',
      status: 'MFSF',
      cardLock: true,
      cardEmission: '60505-0181',
      changeChipPassword: 'Naja haje',
      cardPasswordValidation: 'Paradoxurus hermaphroditus',
      travelNoticeException: 'Climacteris melanura',
      birthDate: '24/11/2021',
      date: '08/08/2021',
      cardChipPassword: '********',
    },
    {
      id: 14,
      name: 'Joni',
      gender: 'Feminino',
      cardNumber: 5108759625590733,
      type: 'mastercard',
      status: 'SNMX',
      cardLock: true,
      cardEmission: '59115-053',
      changeChipPassword: 'Oryx gazella',
      cardPasswordValidation: 'Dicrurus adsimilis',
      travelNoticeException: 'Junonia genoveua',
      birthDate: '02/10/2021',
      date: '18/10/2021',
      cardChipPassword: '********',
    },
    {
      id: 15,
      name: 'Francklin',
      gender: 'Masculino',
      cardNumber: 3552310281394063,
      type: 'jcb',
      status: 'NATR',
      cardLock: true,
      cardEmission: '58118-0157',
      changeChipPassword: 'Neophoca cinerea',
      cardPasswordValidation: 'Zenaida galapagoensis',
      travelNoticeException: 'Mellivora capensis',
      birthDate: '23/04/2021',
      date: '20/07/2021',
      cardChipPassword: '********',
    },
  ];

  /**
   * Retorna todos os extratos financeiros
   * @returns {Array}
   */
  getFakeData() {
    return this.fakeDataList;
  }

  /**
   * Retorna um extrato financeiro baseado no id
   * @param id
   * @returns {FinancialStatement}
   */
  getFakeDataById(id: number): FinancialStatement {
    return this.fakeDataList.filter((data) => data.id === id)[0];
  }
}
